---
- name: Instalar y configurar Apache en puerto 9999
  hosts: webservers
  become: yes
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Modificar puerto 80 a 9999 en ports.conf
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80'
        line: 'Listen 9999'

    - name: Modificar VirtualHost a puerto 9999
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '<VirtualHost \*:80>'
        line: '<VirtualHost *:9999>'

    - name: Reiniciar servicio Apache
      service:
        name: apache2
        state: restarted
